### ISSUE TITLE
Poor UX when content already installed

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#29]
##### GALAXY CLI VERSION
NA

##### CONFIGURATION
NA

##### SUMMARY
Installing version X of content, and then attempting install version X.X of same content results in an ugly traceback, rather than friendly instructions on how to upgrade/downgrade.

Same is true if you install version X, and then attempt to install version X again. You should get a friendly message stating that the content is already installed. 

##### STEPS TO REPRODUCE

Install an early version of some content:

```
ansible-galaxy-cli content-install -t role atestuseraccount.ansible-testing-content,0.1.1
```

Now install a newer version of the same content:

```
ansible-galaxy-cli content-install -t role atestuseraccount.ansible-testing-content,1.1.0
```

##### EXPECTED RESULTS
The client should report the current version that is installed, and provide instructions on how to install the requested version. In the current state of things, the only option is to use the '--force' option, so I would expect to something more friendly, like...

```
Found roles for atestuseraccount.ansible-testing-content, version 0.1.1, already installed in path '~/.ansible/content/roles'
To install roles for atestuseraccount.ansible-testing-content, version 1.1.0, use the --force option, or install to a different path using the ... option
```

##### ACTUAL RESULTS

Received a bunch of text, a traceback, and no suggestions on how to fix the problem:

```
ansible_galaxy_cli.main main:33 - The Galaxy content /Users/chouseknecht/.ansible/content/roles/test-role-a/defaults/main.yml appears to already exist.
Traceback (most recent call last):
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/main.py", line 31, in main
    exit_code = cli.run()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 173, in run
    self.execute()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/__init__.py", line 145, in execute
    fn()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 443, in execute_install
    installed = content.install(force_overwrite=force_overwrite)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/flat_rest_api/content.py", line 555, in install
    force_overwrite=force_overwrite)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/flat_rest_api/content.py", line 336, in _install_for_content_types
    force_overwrite=force_overwrite)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/archive.py", line 424, in extract_by_content_type
    raise exceptions.GalaxyClientError(message)
GalaxyClientError: The Galaxy content /Users/chouseknecht/.ansible/content/roles/test-role-a/defaults/main.yml appears to already exist.
The Galaxy content /Users/chouseknecht/.ansible/content/roles/test-role-a/defaults/main.yml appears to already exist.
```

**Comment by alikins** [comment]
#69 is for the feature part of this. The bug part of this is fixed already, so closing.
