### ISSUE TITLE
info command fail

### ISSUE THREAD

**Issue by chouseknecht** [ansible/mazer#96]
##### GALAXY CLI VERSION
```
Ansible Galaxy CLI, version0.1.0
Darwin, cyclone.local, 17.6.0, Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64, x86_64
2.7.14 (default, Nov 14 2017, 23:24:24)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]/Users/chouseknecht/.pyenv/versions/venv27/bin/python
Using /Users/chouseknecht/.ansible/mazer.yml as config file
```

##### CONFIGURATION
```
    version: '1.0'
    server:
        url: https://galaxy-qa.ansible.com
        ignore_certs: False
    content_path: ~/.ansible/content
    verbosity: 0
```
##### SUMMARY
The `info` command results in a traceback.

##### STEPS TO REPRODUCE

Install a role: 

```
mazer install geerlingguy.apache
```

Then try to get info for the installed role:

```
mazer info geerlingguy.apache
```

##### EXPECTED RESULTS

Receive info about the role.

##### ACTUAL RESULTS

Got the following output and traceback:

```
mazer info geerlingguy.apache
No handlers could be found for logger "ansible_galaxy.rest_api.(http)"

content_type: role
namespace: geerlingguy
repo_name: ansible-role-apache
name: apache
description: Apache 2.x for Linux.
scm: https://github.com/geerlingguy/ansible-role-apache.git

Traceback (most recent call last):
  File "/Users/chouseknecht/.pyenv/versions/venv27/bin/mazer", line 11, in <module>
    load_entry_point('mazer', 'console_scripts', 'mazer')()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/main.py", line 35, in main
    exit_code = cli.run()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 197, in run
    self.execute()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/__init__.py", line 151, in execute
    fn()
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/galaxy.py", line 266, in execute_info
    offline=self.options.offline)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/actions/info.py", line 129, in info_content_specs
    display_callback(data)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy_cli/cli/__init__.py", line 235, in display
    display.display_callback(*args, **kwargs)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/display.py", line 40, in display_callback
    stdout_display_callback(*args, **kwargs)
  File "/Users/chouseknecht/projects/galaxy-cli/ansible_galaxy/display.py", line 27, in stdout_display_callback
    print('%s%s' % (level_prefix, ''.join(args)))
TypeError: sequence item 0: expected string, dict found
```

**Comment by alikins** [comment]
Fixed in #100
